name: jsonrpc docker
on:
  push:
    branches:
    - master
  release:
    types: [published]
  pull_request:
    branches:
    - master
jobs:
  build:
    if: ${{ false }}
    name: build and push
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v2

      - name: build
        run: docker build --tag decentraland/ion-sfu:latest-jsonrpc -f cmd/signal/json-rpc/Dockerfile .

      - name: login
        if: github.event_name == 'release'
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: tag
        if: github.event_name == 'release'
        run: docker tag decentraland/ion-sfu:latest-jsonrpc decentraland/ion-sfu:"$TAG"-jsonrpc
        env:
          TAG: ${{ github.event.release.tag_name }}

      - name: push
        if: github.event_name == 'release'
        run: docker push decentraland/ion-sfu:latest-jsonrpc && docker push decentraland/ion-sfu:"$TAG"-jsonrpc
        env:
          TAG: ${{ github.event.release.tag_name }}
