name: allrpc docker
on:
  push:
    branches:
    - master
  release:
    types: [published]
  pull_request:
    branches:
    - master
jobs:
  build:
    name: build and push
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: cmd/signal/allrpc/Dockerfile
          push: true
          tags: decentraland/ion-sfu:latest-allrpc

      # - name: tag
      #   if: github.event_name == 'release'
      #   run: docker tag decentraland/ion-sfu:latest-allrpc decentraland/ion-sfu:"$TAG"-allrpc
      #   env:
      #     TAG: ${{ github.event.release.tag_name }}

      # - name: push
      #   # if: github.event_name == 'release'
      #   run: docker push decentraland/ion-sfu:latest-allrpc
      #   env:
      #     TAG: ${{ github.event.release.tag_name }}

      # - name: push
      #   if: github.event_name != 'release'
      #   run: docker push decentraland/ion-sfu:latest-allrpc && docker push decentraland/ion-sfu:next-allrpc
      #   env:
      #     TAG: ${{ github.event.release.tag_name }}